# Generated by Django 5.1.6 on 2025-02-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_team_hide_ranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="minigame",
            name="play_count",
            field=models.IntegerField(default=0),
        ),
    ]
