# Generated by Django 5.1.6 on 2025-03-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_commonsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonsetting",
            name="attack_count_ranking_top_n",
            field=models.IntegerField(
                default=10, help_text="被攻擊次數排行榜顯示前 N 名"
            ),
        ),
        migrations.AddField(
            model_name="commonsetting",
            name="hide_attack_count_ranking",
            field=models.BooleanField(default=False, help_text="隱藏被攻擊次數排行榜"),
        ),
        migrations.AddField(
            model_name="commonsetting",
            name="hide_minigame_ranking",
            field=models.BooleanField(
                default=False, help_text="隱藏小遊戲完成數排行榜"
            ),
        ),
        migrations.AddField(
            model_name="commonsetting",
            name="hide_player_ranking",
            field=models.BooleanField(default=False, help_text="隱藏玩家得分排行榜"),
        ),
        migrations.AddField(
            model_name="commonsetting",
            name="hide_team_ranking",
            field=models.BooleanField(default=False, help_text="隱藏隊伍排行榜"),
        ),
        migrations.AddField(
            model_name="commonsetting",
            name="minigame_ranking_top_n",
            field=models.IntegerField(
                default=10, help_text="完成小遊戲數排行榜顯示前 N 名"
            ),
        ),
        migrations.AddField(
            model_name="commonsetting",
            name="player_ranking_top_n",
            field=models.IntegerField(
                default=10, help_text="玩家得分排行榜顯示前 N 名"
            ),
        ),
        migrations.AddField(
            model_name="commonsetting",
            name="team_ranking_top_n",
            field=models.IntegerField(default=10, help_text="隊伍排行榜顯示前 N 名"),
        ),
    ]
