# Generated by Django 5.1.6 on 2025-02-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="number",
        ),
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(default="on99", max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
