# Generated by Django 5.1.6 on 2025-02-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_remove_team_number_team_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="minigame",
            old_name="score",
            new_name="available_chips",
        ),
        migrations.AddField(
            model_name="minigame",
            name="category",
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="minigame",
            name="name",
            field=models.CharField(default="1", max_length=100),
            preserve_default=False,
        ),
    ]
