# Generated by Django 5.1.6 on 2025-02-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_rename_score_minigame_available_chips_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="minigame",
            name="is_displayed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="minigame",
            name="is_limited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="minigame",
            name="limited_time",
            field=models.IntegerField(default=0),
        ),
    ]
