# Generated by Django 5.1.6 on 2025-02-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_minigame_is_displayed_minigame_is_limited_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="hide_ranking",
            field=models.BooleanField(default=False),
        ),
    ]
