# Generated by Django 5.1.6 on 2025-02-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_minigame_play_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="hide_completed_minigame_count",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="hide_name",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="hide_personal_score",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="hide_team",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="team",
            name="hide_team_name",
            field=models.BooleanField(default=False),
        ),
    ]
