# Generated by Django 5.1.6 on 2025-02-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_player_hide_completed_minigame_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attacker_team_bonus",
                    models.IntegerField(default=2, help_text="攻擊者隊伍加分"),
                ),
                (
                    "attacker_player_bonus",
                    models.IntegerField(default=1, help_text="攻擊者玩家加分"),
                ),
                (
                    "attacked_increment",
                    models.IntegerField(default=1, help_text="被攻擊隊伍次數增加"),
                ),
            ],
        ),
    ]
